
server:
  port: 8082

logging:
  level: info

spring:
  dubbo:
    application:
      name: item-web
    registry:
      protocol: zookeeper
      address: 94.191.2.120:2181
    base-package: com.zben.gmall
    protocol:
      name: dubbo
    consumer:
      timeout: 10000    #访问提供端服务的超时时间，默认是1000毫秒
      check: false
  thymeleaf:
    cache: false    #consumer.check 是启动消费端时，是否检查服务端能否正常访问。如果选择true，那启动消费端时，必须保证提供端服务正常，否则接口无法注入。
    mode: LEGACYHTML5 # 松校验
