


server:
  port: 8071

#jdbc
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/gmall?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  dubbo:
    application:
      name: manage-service #服务名，不能跟别的dubbo提供端重复
    registry:
      protocol: zookeeper #指定注册中心协议
      address: 94.191.2.120:2181  #注册中心的地址加端口号
    base-package: com.zben.gmall  #注解方式要扫描的包
    protocol:
      name: dubbo

#mybatis
#开启驼峰
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  level: info